(function(global){
  'use strict';
  const $=id=>document.getElementById(id);
  let scope='50',lastResult=null;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function color(n){if(n<=9)return'yellow';if(n<=19)return'blue';if(n<=29)return'red';if(n<=39)return'black';return'green';}
  function ball(n,small=false,marked=false){return `<span class="dashboard-ball ${small?'small':''} ${color(Number(n))} ${marked?'marked':''}">${Number(n)}</span>`;}
  function balls(nums,small=false,marked=[]){return `<div class="dashboard-balls">${(nums||[]).map(n=>ball(n,small,marked.includes(n))).join('')}</div>`;}
  function reveal(){['dashHero','dashMetrics','dashFusion','dashAIScore','dashCompanion','dashOptimizer','dashBacktest','dashQuick'].forEach(id=>$(id)?.classList.remove('is-hidden'));}
  function errorBox(msg){return `<div class="dashboard-error">${esc(msg)}</div>`;}
  function contribution(label,value){const safe=Math.max(0,Math.min(100,Number(value)||0));return `<div class="dashboard-contrib-row"><span>${esc(label)}</span><div class="dashboard-bar"><i style="width:${Math.max(4,safe)}%"></i></div><b>${Math.round(safe)}</b></div>`;}
  function parseInput(){return global.DashboardAdapter.clean(($('dashComboInput').value||'').split(/[\s,]+/));}
  function setStatus(text){$('dashStatus').textContent=text;}
  function saveNums(nums){localStorage.setItem('haengun_my_nums',JSON.stringify(nums));}

  function renderAssistant(r){const box=$('dashAssistant');box.classList.remove('is-empty');box.innerHTML=`<div class="dashboard-card-head"><div><b>🤖 AI 한줄 판단</b><span>${r.scope==='all'?'전체':`최근 ${r.scope}회`} · ${r.bonus?'보너스 포함':'보너스 제외'}</span></div></div><p>${esc(r.assistant)}</p>`;}
  function renderHero(r){const top=r.topRanked;const f=r.fusion&&!r.fusion.error?r.fusion:null;const target=f?.best?.nums||top?.nums||r.base;const label=f?.best?'Fusion 통합 추천':top?'AI 조합 추천 1위':'현재 분석조합';$('dashHero').innerHTML=`<div class="dashboard-hero-title"><strong>${label}</strong><span>${target.length}개 번호</span></div>${balls(target,false,r.base.filter(n=>target.includes(n)))}<p class="dashboard-hero-note">현재 입력 ${r.base.join('·')} · 전체 출현 ${r.summary.allCount}회 · 현재 범위 ${r.summary.rangeCount}회${r.summary.lastRound?` · 최근 ${r.summary.lastRound}회`:''}</p>`;}
  function renderMetrics(r){const ai=r.topRanked?.aiScore;const f=r.fusion&&!r.fusion.error?r.fusion:null;const p=r.currentPattern;$('dashMetrics').innerHTML=`<div class="dashboard-metric"><b>${ai?.total??'-'}</b><span>AI Score</span><em>${r.topRanked?`${r.topRanked.grade} · 추천 1위`:'6개 추천조합 대기'}</em></div><div class="dashboard-metric"><b>${f?.best?.total??'-'}</b><span>Fusion Score</span><em>${f?.best?`${f.best.replaceCount}개 교체안`:'번호 6개 필요'}</em></div><div class="dashboard-metric"><b>${Math.round(p?.adjusted??0)||'-'}</b><span>Pattern</span><em>Confidence 보정</em></div><div class="dashboard-metric"><b>${Math.round(p?.confidence??0)||'-'}${p?'%':''}</b><span>Confidence</span><em>근거 일관성 지수</em></div>`;}
  function comboBox(title,item,best=false){if(!item)return'';return `<div class="dashboard-combo-box ${best?'best':''}"><b>${title}</b><span>Fusion ${Math.round(item.total||0)} · 교체 ${item.replaceCount||0}개</span>${balls(item.nums,true)}</div>`;}
  function renderFusion(r){const box=$('dashFusion'),f=r.fusion;if(!f||f.error){box.innerHTML=`<div class="dashboard-section-title"><b>🔀 Fusion AI</b><span>번호 6개 기준</span></div>${errorBox(f?.error||'Fusion 분석은 번호 6개 입력 후 표시됩니다.')}`;return;}const c=f.best?.contributions||{};box.innerHTML=`<div class="dashboard-section-title"><b>🔀 Fusion AI 통합추천</b><span>기존 AI 60 · Pattern 20 · 빈도 15 · 유지 5</span></div><div class="dashboard-compare">${comboBox('현재 조합',f.current)}<div class="dashboard-arrow">→</div>${comboBox('통합 추천',f.best,true)}</div><div class="dashboard-change"><span class="dashboard-tag good">유지 ${f.best.kept.join('·')||'-'}</span><span class="dashboard-tag bad">제외 ${f.best.removed.join('·')||'-'}</span><span class="dashboard-tag info">추가 ${f.best.added.join('·')||'-'}</span></div><div class="dashboard-contrib">${contribution('기존 AI 기여',c.classic)}${contribution('Pattern 기여',c.pattern)}${contribution('동반빈도 기여',c.frequency)}${contribution('번호유지 기여',c.preservation)}</div><div class="dashboard-reasons"><b>AI 추천 이유</b>${(f.reasons||[]).map(x=>`<p>✓ ${esc(x)}</p>`).join('')}</div>`;}
  function renderAIScore(r){
    const box=$('dashAIScore'),top=r.topRanked,ai=top?.aiScore,top6=r.dashboardTop6||[],top10=r.dashboardTop10||[],freq=r.dashboardFrequency||[];
    if(r.base.length===6&&top6.length===6&&top10.length){
      const freqTop=freq.slice(0,10);
      box.innerHTML=`<div class="dashboard-section-title"><b>🏆 AI Score TOP6 · TOP10 Consensus</b><span>1개 교체 TOP10 투표</span></div>
        ${balls(top6,false,r.base.filter(n=>top6.includes(n)))}
        <div class="dashboard-change" style="margin-top:11px;grid-template-columns:repeat(3,1fr)">${freqTop.slice(0,6).map(x=>`<span class="dashboard-tag ${r.base.includes(x.n)?'good':'info'}">${x.frequencyRank}위 ${x.n}번 · ${x.count}/10</span>`).join('')}</div>
        <p class="dashboard-placeholder" style="margin-top:10px">AI Score 상위 1개 교체조합 10개에서 번호 등장횟수를 다시 집계했습니다. 동률은 더 높은 TOP10 조합에 먼저 등장한 번호를 우선합니다.</p>
        <details class="fusion-alternatives" style="margin-top:10px"><summary>AI Score TOP10 조합 보기</summary>${top10.map((x,i)=>`<div class="dashboard-optimizer-row"><span>${i+1}위</span><div>${x.nums.map(n=>ball(n,true,r.base.includes(n))).join('')}</div><strong>${Math.round(x.aiScore?.total||0)}점</strong></div>`).join('')}</details>
        <details class="fusion-alternatives"><summary>TOP10 번호 출현빈도 전체 보기</summary>${freq.map(x=>`<div class="dashboard-optimizer-row"><span>${x.frequencyRank}위</span><div>${ball(x.n,true,r.base.includes(x.n))}<b style="margin-left:6px">${x.n}번</b></div><strong>${x.count}/10</strong></div>`).join('')}</details>
        ${top&&ai?`<div class="dashboard-ai-grid" style="margin-top:13px"><div class="dashboard-ai-item"><b>${ai.classic.companion}</b><span>Companion</span><small>TOP10 1위 기준</small></div><div class="dashboard-ai-item"><b>${ai.classic.trend}</b><span>Trend</span><small>최근·장기 흐름</small></div><div class="dashboard-ai-item"><b>${ai.classic.structure}</b><span>Structure</span><small>구간·홀짝 구성</small></div><div class="dashboard-ai-item"><b>${ai.classic.learning}</b><span>Learning</span><small>과거 적중 학습</small></div><div class="dashboard-ai-item"><b>${ai.pattern.pattern}</b><span>Pattern</span><small>반복 패턴성</small></div><div class="dashboard-ai-item"><b>${ai.pattern.replay}</b><span>Replay</span><small>재현성</small></div><div class="dashboard-ai-item"><b>${ai.pattern.flow}</b><span>Flow</span><small>흐름성</small></div><div class="dashboard-ai-item"><b>${ai.pattern.dream}</b><span>Dream</span><small>Dream Chain</small></div></div>`:''}`;
      return;
    }
    if(!top||!ai){box.innerHTML=`<div class="dashboard-section-title"><b>🏆 AI Score</b><span>추천조합</span></div><div class="dashboard-placeholder">동반번호 표본이 부족해 추천조합을 만들지 못했습니다.</div>`;return;}
    box.innerHTML=`<div class="dashboard-section-title"><b>🏆 AI 추천 1위 · ${ai.total}점</b><span>${top.grade} · Confidence ${ai.confidence}%</span></div>${balls(top.nums,false,r.base.filter(n=>top.nums.includes(n)))}<div class="dashboard-ai-grid" style="margin-top:13px"><div class="dashboard-ai-item"><b>${ai.classic.companion}</b><span>Companion</span><small>동반·쌍번호 강도</small></div><div class="dashboard-ai-item"><b>${ai.classic.trend}</b><span>Trend</span><small>최근·장기 흐름</small></div><div class="dashboard-ai-item"><b>${ai.classic.structure}</b><span>Structure</span><small>구간·홀짝 구성</small></div><div class="dashboard-ai-item"><b>${ai.classic.learning}</b><span>Learning</span><small>과거 적중 학습</small></div><div class="dashboard-ai-item"><b>${ai.pattern.pattern}</b><span>Pattern</span><small>반복 패턴성</small></div><div class="dashboard-ai-item"><b>${ai.pattern.replay}</b><span>Replay</span><small>재현성</small></div><div class="dashboard-ai-item"><b>${ai.pattern.flow}</b><span>Flow</span><small>흐름성</small></div><div class="dashboard-ai-item"><b>${ai.pattern.dream}</b><span>Dream</span><small>Dream Chain</small></div></div>`;
  }
  function patternRow(label,item){if(!item)return `<div class="dashboard-pattern-row"><span>${label}</span><div>기록 없음</div><em>-</em></div>`;return `<div class="dashboard-pattern-row"><span>${label}</span><div>${(item.nums||[]).map(n=>ball(n,true)).join('')}</div><em>${item.count||0}회</em></div>`;}
  function renderCompanion(r){const box=$('dashCompanion');const rec=r.companion?.recommend||[];box.innerHTML=`<div class="dashboard-section-title"><b>🤝 동반패턴 AI</b><span>추천번호별 최고 2·3·4조합</span></div>${rec.length?`<div class="dashboard-change" style="margin:0 0 12px"><span class="dashboard-tag info">추천 ${rec.join('·')}</span><span class="dashboard-tag">표본 ${r.companion.rows?.length||0}회</span></div><div class="dashboard-pattern-list">${(r.patterns||[]).map((x,i)=>`<div class="dashboard-pattern-item"><div class="dashboard-pattern-head"><div>${ball(x.candidate,true)}<b>${x.candidate}번</b>${i===0?'<span>최상위</span>':''}</div><span>Index ${x.index?.score||0} · ${x.aiUsage?.label||''}</span></div><div class="dashboard-pattern-combos">${patternRow('2조합',x.two)}${patternRow('3조합',x.three)}${patternRow('4조합',x.four)}</div></div>`).join('')}</div>`:`<div class="dashboard-placeholder">현재 범위에서는 추천 동반번호가 없습니다. 범위를 100회 또는 전체로 바꿔보세요.</div>`}`;}
  function renderAll(r){lastResult=r;reveal();renderAssistant(r);renderHero(r);renderMetrics(r);renderFusion(r);renderAIScore(r);renderCompanion(r);$('dashOptimizerResult').innerHTML=r.base.length===6?'현재 유지와 1·2·3개 교체 결과를 계산할 수 있습니다.':'번호 6개 입력 시 사용할 수 있습니다.';saveNums(r.base);setStatus(`전체 ${(global.LOTTO_DATA||[]).length}개 회차 · 분석 완료`);}
  function analyze(){const nums=parseInput();if(nums.length<2||nums.length>6){setStatus('번호는 2개 이상 6개 이하로 입력하세요.');return;}setStatus('AI 엔진을 통합 계산 중입니다...');setTimeout(()=>{const r=global.DashboardAdapter.analyze(nums,scope,$('dashBonus').checked,{force:true});if(r.error){setStatus(r.error);return;}renderAll(r);},20);}
  function optimizer(){if(!lastResult||lastResult.base.length!==6){$('dashOptimizerResult').innerHTML=errorBox('번호 6개를 먼저 분석하세요.');return;}const btn=$('dashRunOptimizer');btn.disabled=true;btn.textContent='계산 중';$('dashOptimizerResult').textContent='현재 유지와 1·2·3개 교체 후보를 비교하고 있습니다...';setTimeout(()=>{try{const r=global.DashboardAdapter.optimize(lastResult.base,lastResult.scope,lastResult.bonus);if(r.error){$('dashOptimizerResult').innerHTML=errorBox(r.error);return;}$('dashOptimizerResult').innerHTML=`<div class="dashboard-change"><span class="dashboard-tag info">자동 선택: ${r.best.replaceCount}개 교체</span><span class="dashboard-tag">AI 연동 ${Math.round(r.best.score||0)}점</span></div><div class="dashboard-optimizer-table">${r.options.map(x=>`<div class="dashboard-optimizer-row ${x===r.best?'best':''}"><span>${x.replaceCount===0?'현재 유지':`${x.replaceCount}개 교체`}</span><div>${x.nums.map(n=>ball(n,true)).join('')}</div><strong>${Math.round(x.score||0)}점</strong></div>`).join('')}</div>${r.best.replaceCount?`<div class="dashboard-change"><span class="dashboard-tag bad">제외 ${(r.best.removed||[]).join('·')}</span><span class="dashboard-tag good">추가 ${(r.best.added||[]).join('·')}</span></div>`:'<p class="dashboard-placeholder">교체보다 현재 유지가 우세합니다.</p>'}`;}finally{btn.disabled=false;btn.textContent='다시 실행';}},30);}
  function backtest(){const btn=$('dashRunBacktest');btn.disabled=true;btn.textContent='계산 중';$('dashBacktestResult').textContent='최근 50회 워크포워드 검증을 실행하고 있습니다...';setTimeout(()=>{try{const r=global.DashboardAdapter.backtest();if(!r||r.error){$('dashBacktestResult').innerHTML=errorBox(r?.error||'백테스트 결과를 만들지 못했습니다.');return;}$('dashBacktestResult').innerHTML=`<div class="dashboard-change"><span class="dashboard-tag info">판정 ${r.verdict}</span><span class="dashboard-tag">${r.count}개 회차</span></div><div class="dashboard-backtest-grid"><div><b>${r.avgPercentile}</b><span>평균 백분위</span></div><div><b>${r.top25}%</b><span>상위 25%</span></div><div><b>${r.top50}%</b><span>상위 50%</span></div><div><b>${r.highTop25}%</b><span>고신뢰 상위25%</span></div></div><p class="dashboard-placeholder">${esc(r.note)}</p>`;}finally{btn.disabled=false;btn.textContent='다시 실행';}},35);}
  function quick(){if(!lastResult){$('dashQuickResult').innerHTML=errorBox('먼저 조합을 분석하세요.');return;}const q=global.DashboardAdapter.quick($('dashQuickNumber').value,lastResult);if(q.error){$('dashQuickResult').innerHTML=errorBox(q.error);return;}$('dashQuickResult').innerHTML=`<div class="dashboard-quick-result"><div class="dashboard-pattern-head"><div>${ball(q.n)}<b>${q.n}번 빠른조회</b></div><span>${q.frequency}/${q.sourceCount}회 출현</span></div><div class="dashboard-change"><span class="dashboard-tag ${q.selected?'good':''}">${q.selected?'현재 조합 포함':'현재 조합 미포함'}</span><span class="dashboard-tag ${q.recommended?'info':''}">${q.recommended?'동반 추천':'동반지수 '+q.companionIndex}</span>${q.fusionAdded?'<span class="dashboard-tag good">Fusion 추가</span>':''}${q.fusionRemoved?'<span class="dashboard-tag bad">Fusion 제외</span>':''}${q.fusionKept?'<span class="dashboard-tag info">Fusion 유지</span>':''}</div><p class="dashboard-placeholder">최근 출현 ${q.lastRound?`${q.lastRound}회 · ${q.lastDate}`:'기록 없음'} · 동반출현 ${q.companionCount}회</p>${q.links.length?`<div class="dashboard-quick-links">${q.links.map(x=>`<span class="dashboard-tag">${q.n}·${x.n} ${x.count}회</span>`).join('')}</div>`:''}</div>`;}
  function waitData(){if((global.LOTTO_DATA||[]).length){setStatus(`전체 ${global.LOTTO_DATA.length}개 회차를 불러왔습니다.`);const saved=JSON.parse(localStorage.getItem('haengun_my_nums')||'null');if(Array.isArray(saved)&&saved.length>=2)$('dashComboInput').value=saved.slice(0,6).join(' ');return;}setTimeout(waitData,150);}
  function bind(){
    $('dashScope').addEventListener('click',e=>{const b=e.target.closest('[data-scope]');if(!b)return;scope=b.dataset.scope;document.querySelectorAll('#dashScope button').forEach(x=>x.classList.toggle('active',x===b));});
    $('dashAnalyze').addEventListener('click',analyze);$('dashComboInput').addEventListener('keydown',e=>{if(e.key==='Enter')analyze();});
    $('dashUseSaved').addEventListener('click',()=>{const saved=JSON.parse(localStorage.getItem('haengun_my_nums')||'null');if(Array.isArray(saved))$('dashComboInput').value=saved.join(' ');});
    $('dashRunOptimizer').addEventListener('click',optimizer);$('dashRunBacktest').addEventListener('click',backtest);$('dashQuickSearch').addEventListener('click',quick);$('dashQuickNumber').addEventListener('keydown',e=>{if(e.key==='Enter')quick();});
    waitData();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})(window);
