
let lottoData=[],shownCount=5,myNums=loadMyNums(),selectedNums=[myNums[0]],matchRange=50;
const $=id=>document.getElementById(id);

function loadMyNums(){try{const s=JSON.parse(localStorage.getItem("haengun_my_nums")||"null");if(Array.isArray(s)&&s.length===6&&s.every(n=>Number.isInteger(n)&&n>=1&&n<=45))return s;}catch(e){}return[5,14,23,33,42,9];}
function saveMyNums(){localStorage.setItem("haengun_my_nums",JSON.stringify(myNums));}
function setMyNumbers(){const input=prompt("예상번호 6개를 입력하세요.\n예: 5 14 23 33 42 9",myNums.join(" "));if(input===null)return;const nums=input.split(/[\s,]+/).map(v=>Number(v.trim())).filter(v=>Number.isInteger(v));if(nums.length!==6){alert("번호는 6개를 입력해야 합니다.");return;}const u=[...new Set(nums)];if(u.length!==6){alert("중복 번호는 사용할 수 없습니다.");return;}if(u.some(n=>n<1||n>45)){alert("번호는 1부터 45 사이만 가능합니다.");return;}myNums=u.sort((a,b)=>a-b);selectedNums=[myNums[0]];saveMyNums();renderMyCard();renderMatchDetail();alert("예상번호가 저장되었습니다.");}

function injectComboStyle(){const css=`
.pick-slot.active{border:3px solid #ffdc64!important;background:#fff8db!important;transform:scale(1.08);transition:.18s ease}
.combo-selected{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.combo-desc{font-size:13px;color:#667085;margin:6px 0 0}
.history-row.combo-hit{background:#fffdf5}.hit-combo{background:#ffe8a3;color:#8a5b00}.folder-btn{cursor:pointer}
.exact-card{background:linear-gradient(180deg,#fffaf0,#fff);border:1px solid #ffe08a;border-radius:18px;padding:16px;margin:10px 0;box-shadow:0 4px 14px rgba(154,101,0,.12)}
.exact-title{font-size:22px;font-weight:900;color:#8a5b00;margin-bottom:8px}.exact-status{display:inline-block;border-radius:18px;padding:6px 10px;font-size:13px;font-weight:900;margin:6px 0 10px}.exact-hit{background:#ffe8a3;color:#8a5b00}.exact-none{background:#eef2f7;color:#475569}.exact-message{font-size:14px;color:#344054;line-height:1.55;margin-top:8px}.exact-recommend{margin-top:10px;background:#f8fafc;border-radius:12px;padding:10px;font-size:13px;color:#475569}
.companion-card{background:white;border:1px solid #e7edf5;border-radius:16px;padding:14px;margin:10px 0;box-shadow:0 2px 10px rgba(0,0,0,.06)}
.companion-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.companion-title b{font-size:17px;color:#11366b}.companion-title span{font-size:12px;color:#667085}
.companion-recommend{background:#f0f7ff;border:1px solid #cfe7ff;border-radius:14px;padding:10px;margin:10px 0}.companion-recommend strong{display:block;color:#0b63ce;margin-bottom:6px}
.companion-balls{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.companion-list{margin-top:10px}.companion-row{display:grid;grid-template-columns:44px 1fr 56px;align-items:center;gap:8px;border-top:1px solid #eef2f7;padding:8px 0}.companion-row:first-child{border-top:0}.companion-bar{height:9px;background:#eaf4ff;border-radius:10px;overflow:hidden}.companion-bar i{display:block;height:100%;background:#2d8cff;border-radius:10px}.companion-count{text-align:right;color:#11366b;font-weight:900;font-size:13px}.companion-note{font-size:12px;color:#667085;margin-top:8px;line-height:1.4}
`;const st=document.createElement("style");st.textContent=css;document.head.appendChild(st);}

function colorClass(n){n=Number(n);if(n<=9)return"yellow";if(n<=19)return"blue";if(n<=29)return"red";if(n<=39)return"black";return"green";}
function ball(n,small=false,extra=""){return`<span class="ball ${small?"small-ball":""} ${extra} ${colorClass(n)}">${n}</span>`;}
function tinyBall(n,extra=""){return`<span class="ball tiny-ball ${extra} ${colorClass(n)}">${n}</span>`;}
function balls(nums,bonus=null,small=false){let h=`<div class="balls">`+nums.map(n=>ball(n,small)).join("");if(bonus!==null)h+=`<span class="plus">|</span>${ball(bonus,small)}`;return h+`</div>`;}

async function loadData(){try{const r=await fetch("./data/lotto.json?ts="+Date.now());const d=await r.json();if(!Array.isArray(d))throw new Error("lotto.json 배열 아님");lottoData=d.sort((a,b)=>b.round-a.round);renderHome();renderStats();renderRecommend("stat");renderMyCard();renderMatchDetail();}catch(e){console.error(e);if($("statusBox"))$("statusBox").innerHTML="데이터 오류: data/lotto.json을 읽지 못했습니다.";}}
function renderLatest(x){return`<div class="card center"><div class="round-title">${x.round}회</div><div class="draw-date">${x.date} 추첨</div><div class="label">당첨번호</div>${balls(x.numbers)}<div class="label">보너스번호</div>${balls([x.bonus])}</div>`;}
function renderHome(){if(!lottoData.length){if($("statusBox"))$("statusBox").innerHTML="lotto.json 데이터가 비어 있습니다.";return;}const x=lottoData[0];if($("roundInput"))$("roundInput").value=x.round;if($("statusBox"))$("statusBox").outerHTML=`<div id="statusBox">${renderLatest(x)}</div>`;renderRecent();}
function renderRecent(){if(!$("recentList"))return;$("recentList").innerHTML=lottoData.slice(0,shownCount).map((x,i)=>`<div class="row ${i===0?"selected":""}"><div><b>${x.round}회</b><br><span style="font-size:12px;color:#667085">${x.date}</span></div><div>${String(x.date).slice(5)}</div><div class="nums">${x.numbers.map(n=>ball(n,true)).join("")}</div><div>${ball(x.bonus,true)}</div></div>`).join("");}
function renderMyCard(){if($("myNumbers"))$("myNumbers").innerHTML=myNums.map(n=>ball(n)).join("");const all=lottoData.flatMap(x=>x.numbers||[]),cnt=myNums.reduce((s,n)=>s+all.filter(v=>v===n).length,0);if($("appearCount"))$("appearCount").textContent=cnt+"회";const idx=lottoData.findIndex(x=>(x.numbers||[]).some(n=>myNums.includes(n)));if($("recentAppear"))$("recentAppear").textContent=idx>=0?`${idx+1}회 전`:"-";if($("missGap"))$("missGap").textContent=idx>=0?`${idx+1}회`:"-";}
function counter(){const m={};for(let i=1;i<=45;i++)m[i]=0;lottoData.forEach(x=>(x.numbers||[]).forEach(n=>m[n]++));return m;}
function renderStats(){if(!$("hotBalls"))return;const c=counter(),a=Object.entries(c).map(([n,v])=>[Number(n),v]),hot=[...a].sort((a,b)=>b[1]-a[1]).slice(0,10),cold=[...a].sort((a,b)=>a[1]-b[1]).slice(0,10);$("hotBalls").innerHTML=hot.map(x=>ball(x[0])).join("");$("coldBalls").innerHTML=cold.map(x=>ball(x[0])).join("");if($("hotList"))$("hotList").innerHTML=hot.map(x=>`${x[0]}번 : ${x[1]}회`).join("<br>");if($("coldList"))$("coldList").innerHTML=cold.map(x=>`${x[0]}번 : ${x[1]}회`).join("<br>");const nums=lottoData.flatMap(x=>x.numbers||[]),odd=nums.filter(n=>n%2).length;if($("ratioBox"))$("ratioBox").innerHTML=`홀수 ${odd}회 / 짝수 ${nums.length-odd}회`;}
function randomNums(){let a=[];while(a.length<6){let n=Math.floor(Math.random()*45)+1;if(!a.includes(n))a.push(n)}return a.sort((x,y)=>x-y);}
function balancedNums(){let nums=[];[[1,9],[10,19],[20,29],[30,39],[40,45]].forEach(z=>{let n=Math.floor(Math.random()*(z[1]-z[0]+1))+z[0];if(!nums.includes(n))nums.push(n)});while(nums.length<6){let n=Math.floor(Math.random()*45)+1;if(!nums.includes(n))nums.push(n)}return nums.sort((a,b)=>a-b);}
function recommendStat(){const c=counter(),a=Object.entries(c).map(([n,v])=>[Number(n),v]),hot=[...a].sort((a,b)=>b[1]-a[1]).slice(0,18).map(x=>x[0]),cold=[...a].sort((a,b)=>a[1]-b[1]).slice(0,20).map(x=>x[0]);let nums=[];while(nums.length<3){let n=hot[Math.floor(Math.random()*hot.length)]||Math.floor(Math.random()*45)+1;if(!nums.includes(n))nums.push(n)}while(nums.length<6){let n=cold[Math.floor(Math.random()*cold.length)]||Math.floor(Math.random()*45)+1;if(!nums.includes(n))nums.push(n)}return nums.sort((a,b)=>a-b);}
function renderRecommend(type="stat"){if(!$("recommendBalls"))return;const nums=type==="random"?randomNums():type==="balance"?balancedNums():recommendStat();$("recommendBalls").innerHTML=nums.map(n=>ball(n)).join("");}
function dreamRecommend(){if(!$("dreamInput")||!$("dreamResult"))return;const k=$("dreamInput").value.trim()||"행운";let seed=[...k].reduce((s,ch)=>s+ch.charCodeAt(0),0),nums=[];while(nums.length<6){seed=(seed*9301+49297)%233280;let n=seed%45+1;if(!nums.includes(n))nums.push(n)}nums.sort((a,b)=>a-b);$("dreamResult").innerHTML=`<h3>${k} 꿈 추천번호</h3>${balls(nums)}<p class="note">꿈 키워드 기반 개인용 추천입니다.</p>`;}

function showPage(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));if($(p))$(p).classList.add("active");document.querySelectorAll(".tab,.bottom-btn").forEach(x=>x.classList.toggle("active",x.dataset.page===p));const d=p==="match";if($("mainHeader"))$("mainHeader").classList.toggle("hidden",d);if($("detailHeader"))$("detailHeader").classList.toggle("hidden",!d);if($("bottomNav"))$("bottomNav").classList.toggle("hidden",d);if(d)renderMatchDetail();}
function toggleNumber(n){if(selectedNums.includes(n)){if(selectedNums.length>1)selectedNums=selectedNums.filter(v=>v!==n)}else selectedNums.push(n);selectedNums.sort((a,b)=>a-b);renderMatchDetail();}
function renderPickRow(){if(!$("pickRow"))return;$("pickRow").innerHTML=myNums.map(n=>{const active=selectedNums.includes(n);return`<button class="pick-slot ${active?"active":""}" onclick="toggleNumber(${n})">${ball(n,false,active?"selected-ball":"")}</button>`}).join("");}
function includeBonus(){return $("includeBonus")?$("includeBonus").checked:true;}
function rowPool(row){return includeBonus()?[...(row.numbers||[]),row.bonus]:[...(row.numbers||[])];}
function rowHasAllSelected(row){const pool=rowPool(row);return selectedNums.every(n=>pool.includes(n));}
function exactWinningRows(){if(selectedNums.length!==6)return[];const key=selectedNums.slice().sort((a,b)=>a-b).join(",");return lottoData.filter(row=>(row.numbers||[]).slice().sort((a,b)=>a-b).join(",")===key).sort((a,b)=>b.round-a.round);}
function comboMatches(){const src=matchRange==="all"?lottoData:lottoData.slice(0,Number(matchRange));return src.filter(rowHasAllSelected).sort((a,b)=>b.round-a.round);}
function comboStats(){const all=lottoData.filter(rowHasAllSelected).sort((a,b)=>b.round-a.round),range=comboMatches(),last=all[0],gap=last?lottoData.findIndex(x=>x.round===last.round)+1:"-";return{allMatches:all,rangeMatches:range,last,lastGap:gap};}
function summaryTarget(){return $("comboSummary")||$("numberSummary");}
function renderExactAnalysis(){const exact=exactWinningRows(),numsHtml=selectedNums.map(n=>ball(n)).join(""),hit=exact.length>0,latest=exact[0],msg=hit?`${latest.round}회 당첨번호와 완전일치한 기록이 있습니다.`:"역대 당첨번호와 완전일치한 기록이 없습니다.",rec=hit?"추천: 이미 당첨 이력이 있는 조합입니다. 일부 번호를 바꿔 새 조합으로 5개 분석도 함께 확인해 보세요.":"추천: 역대 미출현 조합입니다. 희소성은 있지만 당첨을 보장하지는 않습니다. 번호 1~2개를 바꿔 5개 조합 분석도 함께 확인해 보세요.";return`<div class="exact-card"><div class="exact-title">🎯 완전일치 분석</div><div class="combo-selected">${numsHtml}</div><span class="exact-status ${hit?"exact-hit":"exact-none"}">${hit?"완전일치 조합 존재":"역대 미출현 조합"}</span><div class="exact-message">${msg}</div><div class="summary-metrics" style="margin-top:12px;border:1px solid #eef2f7;border-radius:12px;overflow:hidden"><div><b>${exact.length}회</b><span>완전일치</span></div><div><b>${hit?latest.round+"회":"-"}</b><span>최근 회차</span></div><div><b>${hit?latest.date:"-"}</b><span>추첨일</span></div><div><b>${hit?lottoData.findIndex(x=>x.round===latest.round)+1+"회":"-"}</b><span>미출현</span></div><div><b>당첨번호</b><span>비교기준</span></div></div><div class="exact-recommend">${rec}</div></div>`;}
function renderComboSummary(){const target=summaryTarget();if(!target)return;if(selectedNums.length===6){target.innerHTML=renderExactAnalysis();return;}const s=comboStats(),numsHtml=selectedNums.map(n=>ball(n)).join("");target.innerHTML=`<div class="summary-card"><div class="summary-top"><div><div class="combo-selected">${numsHtml}</div><div class="summary-num">${selectedNums.length}개 번호 조합 분석</div><p class="combo-desc">선택한 번호가 같은 회차에 동시에 나온 기록입니다.</p></div></div><div class="summary-metrics"><div><b>${s.allMatches.length}회</b><span>전체 출현</span></div><div><b>${s.rangeMatches.length}회</b><span>현재 범위</span></div><div><b>${s.last?s.last.round+"회":"-"}</b><span>최근 출현</span></div><div><b>${s.lastGap}</b><span>미출현 기간</span></div><div><b>${includeBonus()?"포함":"제외"}</b><span>보너스</span></div></div></div>`;}

function companionSourceRows(){const src=matchRange==="all"?lottoData:lottoData.slice(0,Number(matchRange));return src.filter(rowHasAllSelected);}
function companionAnalysis(){const rows=companionSourceRows(),counts={};for(let i=1;i<=45;i++)counts[i]=0;rows.forEach(row=>{const nums=includeBonus()?[...(row.numbers||[]),row.bonus]:[...(row.numbers||[])];nums.forEach(n=>{if(!selectedNums.includes(n))counts[n]++;});});const top=Object.entries(counts).map(([n,c])=>({n:Number(n),count:c})).filter(x=>x.count>0).sort((a,b)=>b.count-a.count||a.n-b.n).slice(0,10);return{rows,top,recommend:top.slice(0,3).map(x=>x.n)};}
function renderCompanionAnalysis(){const old=$("companionAnalysis");if(old)old.remove();const target=summaryTarget();if(!target)return;const {rows,top,recommend}=companionAnalysis(),max=top.length?top[0].count:1;let html=`<div id="companionAnalysis" class="companion-card"><div class="companion-title"><b>동반출현 분석</b><span>${matchRange==="all"?"전체 회차":"최근 "+matchRange+"회"}</span></div><div class="combo-desc">${selectedNums.map(n=>n+"번").join(", ")} 기준으로 함께 자주 나온 번호입니다.</div>`;html+=recommend.length?`<div class="companion-recommend"><strong>AI 추천 동반번호</strong><div class="companion-balls">${recommend.map(n=>ball(n,true)).join("")}</div></div>`:`<div class="companion-recommend"><strong>AI 추천 동반번호</strong><div class="combo-desc">현재 범위에서 추천할 동반번호가 없습니다. 전체 회차로 바꿔보세요.</div></div>`;html+=`<div class="companion-list">`;html+=top.length?top.map(x=>`<div class="companion-row"><div>${ball(x.n,true)}</div><div class="companion-bar"><i style="width:${Math.max(8,Math.round(x.count/max*100))}%"></i></div><div class="companion-count">${x.count}회</div></div>`).join(""):`<div class="card center">동반출현 기록이 없습니다.</div>`;html+=`</div><div class="companion-note">분석 기준: 선택번호가 포함된 ${rows.length}개 회차에서 추가로 함께 나온 번호를 집계했습니다.</div></div>`;target.insertAdjacentHTML("afterend",html);}

function renderMatchHistory(){if(!$("matchHistory"))return;const matches=selectedNums.length===6?exactWinningRows():comboMatches();if(!matches.length){const msg=selectedNums.length===6?"선택한 6개 번호와 완전일치한 당첨 회차가 없습니다.":`선택한 ${selectedNums.length}개 번호가 동시에 나온 회차가 없습니다.`;$("matchHistory").innerHTML=`<div class="card center">${msg}</div>`;return;}$("matchHistory").innerHTML=matches.map(x=>{const hitCount=selectedNums.filter(n=>(x.numbers||[]).includes(n)).length,bonusHit=selectedNums.includes(x.bonus),tagText=selectedNums.length===6?"완전":`${hitCount}${bonusHit?"+B":""}개`,nums=x.numbers.map(n=>tinyBall(n,selectedNums.includes(n)?"selected-ball":"")).join("");return`<div class="history-row combo-hit"><div class="round-cell"><b>${x.round}회</b><span>${x.date}</span></div><div>${String(x.date).slice(5)}</div><div class="history-balls">${nums}</div><div>${tinyBall(x.bonus,selectedNums.includes(x.bonus)?"selected-ball":"")}</div><div><span class="hit-tag hit-combo">${tagText}</span></div></div>`}).join("");}
function renderMatchDetail(){if(!lottoData.length)return;renderPickRow();renderComboSummary();renderCompanionAnalysis();renderMatchHistory();}
function bindEvents(){document.querySelectorAll(".tab,.bottom-btn").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));if($("searchBtn"))$("searchBtn").onclick=()=>{const r=Number($("roundInput").value),x=lottoData.find(v=>v.round===r);if(x)$("statusBox").innerHTML=renderLatest(x);else alert("회차 정보를 찾을 수 없습니다.");};if($("moreBtn"))$("moreBtn").onclick=()=>{shownCount+=5;renderRecent()};if($("detailBtn"))$("detailBtn").onclick=()=>showPage("match");if($("backHome"))$("backHome").onclick=()=>showPage("home");if($("statRecommend"))$("statRecommend").onclick=()=>renderRecommend("stat");if($("balanceRecommend"))$("balanceRecommend").onclick=()=>renderRecommend("balance");if($("randomRecommend"))$("randomRecommend").onclick=()=>renderRecommend("random");if($("dreamBtn"))$("dreamBtn").onclick=dreamRecommend;document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");matchRange=b.dataset.range;renderMatchHistory();renderComboSummary();renderCompanionAnalysis();});if($("includeBonus"))$("includeBonus").onchange=()=>renderMatchDetail();document.querySelectorAll(".folder-btn").forEach(btn=>btn.onclick=setMyNumbers);}
injectComboStyle();bindEvents();loadData();
