(function(global){'use strict';
const clean=a=>[...new Set((a||[]).map(Number).filter(n=>n>=1&&n<=45))].sort((x,y)=>x-y);
const clamp=n=>Math.max(0,Math.min(100,Math.round(Number(n)||0)));
const numsOf=r=>clean(r&&r.numbers);
function freq(rows,bonus=true){const m=Array(46).fill(0);rows.forEach(r=>{numsOf(r).forEach(n=>m[n]++);if(bonus&&r.bonus)m[Number(r.bonus)]++});return m}
function topFromMap(m,exclude=[],limit=12){const ex=new Set(exclude);return Array.from({length:45},(_,i)=>({n:i+1,count:m[i+1]||0})).filter(x=>!ex.has(x.n)).sort((a,b)=>b.count-a.count||a.n-b.n).slice(0,limit)}
function parseUser(raw){return clean(String(raw||'').trim().split(/[^0-9]+/).filter(Boolean))}
function dreamMap(keyword){const d={"물":[1,7,17,26,32,42],"바다":[7,17,26,34,42,45],"새":[5,11,17,23,31,42],"불":[3,9,18,27,36,45],"돈":[8,14,22,33,40,45],"돼지":[3,8,18,28,38,43],"뱀":[4,13,22,31,40,44],"용":[9,18,27,36,44,45],"옷":[6,12,21,30,39,42],"차":[5,14,23,32,41,45],"도자기":[4,12,24,29,34,42],"그릇":[4,12,21,29,36,42],"얼굴":[1,11,20,28,37,45],"행운":[7,14,21,28,35,42]};const keys=Object.keys(d).filter(k=>keyword.includes(k));if(keys.length)return clean(keys.flatMap(k=>d[k])).slice(0,6);let seed=[...keyword].reduce((s,c)=>s+c.charCodeAt(0),0)||12345,out=[];while(out.length<6){seed=(seed*9301+49297)%233280;const n=seed%45+1;if(!out.includes(n))out.push(n)}return out.sort((a,b)=>a-b)}
function companion(base,rows){const counts=Array(46).fill(0),baseSet=new Set(base);rows.forEach(r=>{const pool=clean([...numsOf(r),r.bonus]);if(!base.some(n=>pool.includes(n)))return;pool.forEach(n=>{if(!baseSet.has(n))counts[n]++})});return topFromMap(counts,base,15)}
function fill(base,candidates){const out=clean(base).slice(0,6);for(const x of candidates){const n=Number(x.n??x);if(out.length>=6)break;if(!out.includes(n))out.push(n)}return out.sort((a,b)=>a-b)}
function patternCandidates(rows,base){const byRound=new Map(rows.map(r=>[Number(r.round),r])),gaps=[2,4,6,8,10,12,14,16,18,20,22,24,3,6,9,12,15],m=Array(46).fill(0);const sample=rows.filter(r=>base.some(n=>numsOf(r).includes(n))).slice(0,50);sample.forEach(r=>gaps.forEach(g=>{const p=byRound.get(Number(r.round)-g);if(p)clean([...numsOf(p),p.bonus]).forEach(n=>m[n]++)}));return topFromMap(m,[],15)}
function rankNumber(n,ctx){const max=(a)=>Math.max(...a.slice(1),1);const f=ctx.allFreq[n]/max(ctx.allFreq)*35,rec=ctx.recentFreq[n]/max(ctx.recentFreq)*25,comp=(ctx.compMap[n]||0)/Math.max(...ctx.compMap,1)*25,pat=(ctx.patternMap[n]||0)/Math.max(...ctx.patternMap,1)*15;return f+rec+comp+pat}
function finalCombo(seed,rows){const allFreq=freq(rows),recentFreq=freq(rows.slice(0,Math.min(50,rows.length))),comp=companion(seed,rows),compMap=Array(46).fill(0);comp.forEach(x=>compMap[x.n]=x.count);const pats=patternCandidates(rows,seed),patternMap=Array(46).fill(0);pats.forEach(x=>patternMap[x.n]=x.count);const pool=Array.from({length:45},(_,i)=>i+1).sort((a,b)=>rankNumber(b,{allFreq,recentFreq,compMap,patternMap})-rankNumber(a,{allFreq,recentFreq,compMap,patternMap})||a-b);const preserved=seed.slice(0,Math.min(3,seed.length));return fill(preserved,pool.map(n=>({n})))}
function consensus(combo,rows,seed){const all=freq(rows),recent=freq(rows.slice(0,50)),comp=companion(seed,rows),cm=Array(46).fill(0);comp.forEach(x=>cm[x.n]=x.count);const maxA=Math.max(...all,1),maxR=Math.max(...recent,1),maxC=Math.max(...cm,1);const details=combo.map(n=>({n,score:clamp(all[n]/maxA*38+recent[n]/maxR*30+cm[n]/maxC*32)}));return {score:clamp(details.reduce((s,x)=>s+x.score,0)/(details.length||1)),details}}
function hits(combo,target,includeBonus){const win=numsOf(target),normal=combo.filter(n=>win.includes(n));const bonus=includeBonus&&combo.includes(Number(target.bonus));return {normal:normal.length,bonus,total:normal.length+(bonus?1:0),numbers:normal}}
function score(combo,rows,seed){const c=consensus(combo,rows,seed);const f=freq(rows),vals=combo.map(n=>f[n]),avg=vals.reduce((a,b)=>a+b,0)/(vals.length||1),max=Math.max(...f,1);const odd=combo.filter(n=>n%2).length,structure=Math.max(0,100-Math.abs(3-odd)*18);return clamp(c.score*.55+(avg/max*100)*.30+structure*.15)}
function run(opts){const all=(opts.data||[]).slice().sort((a,b)=>Number(b.round)-Number(a.round)),target=all.find(r=>Number(r.round)===Number(opts.round));if(!target)throw new Error('검증 회차를 찾을 수 없습니다.');let history=all.filter(r=>Number(r.round)<Number(target.round));if(opts.scope!=='all')history=history.slice(0,Number(opts.scope));if(history.length<20)throw new Error('이전 학습 데이터가 부족합니다.');const user=parseUser(opts.userNums),dream=String(opts.dreamKeyword||'').trim(),base=user.length?user:(dream?dreamMap(dream):topFromMap(freq(history.slice(0,50)),[],6).map(x=>x.n));const comp=companion(base,history);const preview=fill(base.slice(0,4),comp);const p1=fill(preview.slice(0,4),patternCandidates(history,preview));const p2=finalCombo(p1,history);const p3=finalCombo([...p2.slice(0,3),...preview.slice(0,2)],history);const aiFinal=finalCombo([...p2.slice(0,3),...p3.slice(0,2)],history);const stages=[['입력/기본번호',base],['Dream Preview',preview],['Chain 1',p1],['Chain 2',p2],['Chain 3',p3],['AI Final',aiFinal]].map(([name,nums])=>({name,nums:fill(nums,topFromMap(freq(history),nums,6)),hit:hits(fill(nums,topFromMap(freq(history),nums,6)),target,opts.includeBonus),score:score(fill(nums,topFromMap(freq(history),nums,6)),history,base)}));const con=consensus(aiFinal,history,base);return {round:Number(target.round),date:target.date,target:{numbers:numsOf(target),bonus:Number(target.bonus)},historyCount:history.length,scope:opts.scope,stages,consensus:con,aiScore:score(aiFinal,history,base),noFutureLeak:history.every(r=>Number(r.round)<Number(target.round))}}
async function runBatch(opts,onProgress){const all=(opts.data||[]).slice().sort((a,b)=>Number(b.round)-Number(a.round));const eligible=all.filter(r=>Number(r.round)>30).slice(0,Number(opts.count));const results=[];for(let i=eligible.length-1;i>=0;i--){const target=eligible[i];try{results.push(run({...opts,round:target.round}))}catch(e){}if(onProgress)onProgress((eligible.length-i)/eligible.length);if(i%8===0)await new Promise(r=>setTimeout(r,0))}return results.sort((a,b)=>b.round-a.round)}
global.BacktestEngine=Object.freeze({version:'1.0.1',run,runBatch,parseUser,dreamMap});
})(window);
